<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class UpdateBuildingsInsertBasicData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('buildings', function (Blueprint $table) {
        });

        DB::table('buildings')->insert([
            /*
            [
                'building_name' => '',
                'description' => '',
                'fe' => ,
                'lut' => ,
                'cry' => ,
                'h2o' => ,
                'h2' => ,
                'prod_fe' => ,
                'prod_lut' => ,
                'prod_cry' => ,
                'prod_h2o' => ,
                'prod_h2' => ,
                'cost_fe' => ,
                'cost_lut' => ,
                'cost_cry' => ,
                'cost_h2o' => ,
                'cost_h2' => ,
                'store_fe' => ,
                'store_lut' => ,
                'store_cry' => ,
                'store_h2o' => ,
                'store_h2' => ,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => ,
                'decrease_ships_timeBy' => ,
                'decrease_defense_timeBy' => ,
                'decrease_building_timeBy' => ,
                'dynamic_buildtime' => ,
                'initial_buildtime' =>
            ],
            */
            // Kommandozentrale
            [
                'building_name' => 'Kommandozentrale',
                'description' => 'Reduziert Bauzeit je weitere Stufe um 10%',
                'fe' => 500,
                'lut' => 200,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 500,
                'store_lut' => 500,
                'store_cry' => 0,
                'store_h2o' => 500,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 10,
                'dynamic_buildtime' => 0,
                'initial_buildtime' => 21600,
                'points' => 5
            ],
            // Forschungszentrum
            [
                'building_name' => 'Forschungszentrum',
                'description' => 'Ermöglicht das Forschen. Reduziert je weitere Stufe die Forschungszeit um 10%',
                'fe' => 300,
                'lut' => 100,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => true,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 10,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 1200,
                'points' => 3
            ],
            // Eisenmine
            [
                'building_name' => 'Eisenmine',
                'description' => 'Fördert Eisen',
                'fe' => 250,
                'lut' => 20,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 16,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 1200,
                'points' => 1
            ],
            // Lutinumraffinerie
            [
                'building_name' => 'Lutinumraffinerie',
                'description' => 'Fördert Lutinum',
                'fe' => 130,
                'lut' => 20,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 10,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 1200,
                'points' => 1
            ],
            // Bohrturm
            [
                'building_name' => 'Bohrturm',
                'description' => 'Fördert Wasser',
                'fe' => 100,
                'lut' => 20,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 20,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 1200,
                'points' => 1
            ],
            // Chemiefabrik
            [
                'building_name' => 'Chemiefabrik',
                'description' => 'Erzeugt Wasserstoff aus Wasser',
                'fe' => 350,
                'lut' => 20,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 5,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 20,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 2700,
                'points' => 3
            ],
            // Erw., Chemiefabrik
            [
                'building_name' => 'Erweiterte Chemiefabrik',
                'description' => 'Eine verbesserte Form der Chemiefabrik',
                'fe' => 20000,
                'lut' => 15000,
                'cry' => 0,
                'h2o' => 2000,
                'h2' => 1000,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 50,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 100,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 4800,
                'points' => 100
            ],
            // Schiffswerft
            [
                'building_name' => 'Schiffswerft',
                'description' => 'Ermöglicht den Bau von Raumschiffen. Reduziert je weitere Stufe die Bauzeit um 10%',
                'fe' => 2000,
                'lut' => 4000,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 20,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => true,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 10,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 5100,
                'points' => 75
            ],
            // Kristallfabrik
            [
                'building_name' => 'Kristallfabrik',
                'description' => 'Erzeugt Kristalle',
                'fe' => 10000,
                'lut' => 12500,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 500,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 5,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 1,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 5400,
                'points' => 10
            ],
            // Eisenlager
            [
                'building_name' => 'Eisenlager',
                'description' => 'Erhöht die maximale Lagerkapazität für Eisen',
                'fe' => 2000,
                'lut' => 500,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 40000,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 0,
                'initial_buildtime' => 14400,
                'points' => 1
            ],
            // Lutinumlager
            [
                'building_name' => 'Lutinumlager',
                'description' => 'Erhöht die maximale Lagerkapazität für Lutinum',
                'fe' => 500,
                'lut' => 2000,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 40000,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 0,
                'initial_buildtime' => 14400,
                'points' => 1
            ],
            // Kristallspeicher
            [
                'building_name' => 'Kristallspeicher',
                'description' => 'Erhöht die maximale Lagerkapazität für Kristalle',
                'fe' => 8000,
                'lut' => 16000,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 1000,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 500,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 0,
                'initial_buildtime' => 28800,
                'points' => 3
            ],
            // Wassertank
            [
                'building_name' => 'Wassertank',
                'description' => 'Erhöht die maximale Lagerkapazität für Wasser',
                'fe' => 500,
                'lut' => 500,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 40000,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 0,
                'initial_buildtime' => 14400,
                'points' => 1
            ],
            // Wasserstoffbehälter
            [
                'building_name' => 'Wasserstoffbehälter',
                'description' => 'Erhöht die maximale Lagerkapazität für Wasserstoff',
                'fe' => 2000,
                'lut' => 2000,
                'cry' => 0,
                'h2o' => 500,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 4000,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 0,
                'initial_buildtime' => 21600,
                'points' => 3
            ],
            // Lagerhalle
            [
                'building_name' => 'Lagerhalle',
                'description' => 'Eine Kombination aus Eisenlager, Lutinumlager und Wassertank mit höherer Kapazität',
                'fe' => 5000,
                'lut' => 2000,
                'cry' => 0,
                'h2o' => 1000,
                'h2' => 0,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 100000,
                'store_lut' => 100000,
                'store_cry' => 0,
                'store_h2o' => 100000,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 0,
                'initial_buildtime' => 27000,
                'points' => 15
            ],
            // Verteidigungsstation
            [
                'building_name' => 'Verteidigungsstation',
                'description' => 'Ermöglicht es Verteidigungsanlagen zu errichten. Reduziert je weitere Stufe die Bauzeit für Verteidigungsanlagen um 10%.',
                'fe' => 400,
                'lut' => 400,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 20,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => true,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 10,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 3600,
                'points' => 10
            ],
            // Radarturm
            [
                'building_name' => 'Radarturm',
                'description' => 'Forschrittliche Technologie zum Überwachen des Weltraums. Stört feindliche Sonden.',
                'fe' => 75000,
                'lut' => 40000,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 5000,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 30000,
                'points' => 25
            ],
            // Plasmakraftwerk
            [
                'building_name' => 'Plasmakraftwerk',
                'description' => 'Kraftwerk zum Betrieb des Schildgenerators. Verbraucht Wasserstoff.',
                'fe' => 50000,
                'lut' => 65000,
                'cry' => 0,
                'h2o' => 0,
                'h2' => 10000,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 20,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 14400,
                'points' => 55
            ],
            // Schildgenerator
            [
                'building_name' => 'Schildgenerator',
                'description' => 'Globaler Verteidigungschild der den Planeten umhüllt. Wird vom Plasmakraftwerk versorgt.',
                'fe' => 100000,
                'lut' => 35000,
                'cry' => 50,
                'h2o' => 0,
                'h2' => 25000,
                'prod_fe' => 0,
                'prod_lut' => 0,
                'prod_cry' => 0,
                'prod_h2o' => 0,
                'prod_h2' => 0,
                'cost_fe' => 0,
                'cost_lut' => 0,
                'cost_cry' => 0,
                'cost_h2o' => 0,
                'cost_h2' => 0,
                'store_fe' => 0,
                'store_lut' => 0,
                'store_cry' => 0,
                'store_h2o' => 0,
                'store_h2' => 0,
                'allows_research' => false,
                'allows_ships' => false,
                'allows_defense' => false,
                'decrease_research_timeBy' => 0,
                'decrease_ships_timeBy' => 0,
                'decrease_defense_timeBy' => 0,
                'decrease_building_timeBy' => 0,
                'dynamic_buildtime' => 1,
                'initial_buildtime' => 36000,
                'points' => 75
            ],

        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('buildings', function (Blueprint $table) {
            //
        });
    }
}
